### Shanil V2 ###
### Creates a Internal Elastic Load Balancer fronting an Autoscaling Group deploying EC2 Instances in a Prvate Range  ### 

AWSTemplateFormatVersion: 2010-09-09
Description: Provisions an EC2 Fleet in a Private Subnet for Back-End Services using a launch template defined below.
### Configure Parameters as needed ###

Parameters:
  KeyPair:
    Description: Please select Key Pair for remote conenctivity for any EC2 Instances deployed using this template.
    Type: AWS::EC2::KeyPair::KeyName
  
  AMIid:
    Description: The following AMI ID consists of an Amazon AMI Linux 2. 
    Type: AWS::EC2::Image::Id
    Default: ami-09ead922c1dad67e4  
  
  InstanceSize: 
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large

  ASGInstanceName:
    Description: Name of your EC2 Fleet Instances
    Type: String
    Default: asg-ec2-priv-001 

  ASGName:
    Description: Name of ASG Instance
    Type: String
    Default: asg-ec2-priv-001 

  ASGGroupMin:
    Description: Min No. of Instances you require running at all times.
    Type: String
    Default: "1"
    
  ASGGroupMax:
    Description: Max No. of Instances you are willing to spin up
    Type: String
    Default: "3"

  ASGGroupDesired:
    Description: Your desired No. of Instances (consider Availablity and Reduntancy)
    Type: String
    Default: "1"

  ALBName:
    Description: Name of your Application Load Balancer sitting in front of your Private EC2 Fleet 
    Type: String
    Default: "alb-priv-001"
  
  ALBHealthIntervalSec:
    Description: Define the healthcheck period you require.
    Type: String
    Default: "30"

  HealthCheckPath:
    Description: Define your Health Check Path
    Type: String
    Default: "/healthcheck.html"

  ALBHealthPort:
    Description: Define the port for healthcheck (80 is default however please change)
    Type: String
    Default: "80"

  ALBHealthTCP:
    Description: Protocol used for healthcheck (HTTP)
    Type: String
    Default: "HTTP"
    
  ALBHealthTimeout:
    Description: Time out between healthchecks
    Type: String
    Default: "15"

  ALBHealthThreshold:
    Description: ALB Health Threshold Count
    Type: String
    Default: "5"

  ALBPort:
    Description: Port forwarded to Target Group
    Type: String
    Default: "80"

  ALBProtocol:
    Description: Protocol forwarded to Target Group
    Type: String
    Default: "HTTP"

  SecurityGroupPrivate:
    Description: Specify the Security Group used for Private Ranges
    Type: "AWS::EC2::SecurityGroup::Id"

### ASG Launch Template and Group
Resources:
### Launch Template
  ASGPrivateEC2LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: ASGPrivateEC2
      LaunchTemplateData:
        InstanceType: !Ref InstanceSize
        ImageId: !Ref AMIid
        KeyName: !Ref KeyPair
        SecurityGroupIds:
          - !ImportValue multi-az-vpc-sg-private
          - !ImportValue multi-az-vpc-sg-private-mgmt
        UserData:
          Fn::Base64: |
             #!/bin/bash
             yum update -y # Update packages
             amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2 #Install LAMP packages
             yum install -y httpd mariadb-server    
             echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
             curl http://169.254.169.254/latest/meta-data/public-hostname > /var/www/html/index.html #Creates a simple page with DNS name and ALB/CLB Monitor url.
             echo "<html><h1>Healthcheck Test Page</h1></html>" > /var/www/html/healthcheck.html     
             usermod -a -G apache ec2-user # Assigns Perms to Dirs.
             chown -R ec2-user:apache /var/www
             chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
             find /var/www -type f -exec sudo chmod 0664 {} \;
             systemctl start httpd && systemctl enable httpd # starts HTTPD and Maria DB
             systemctl start mariadb && systemctl enable mariadb            
### Autoscale Group        
  ASGPrivateEC2Group:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    DependsOn: "ASGPrivateEC2LaunchTemplate"
    Properties:
      MaxSize: !Ref ASGGroupMax
      MinSize: !Ref ASGGroupMin
      DesiredCapacity: !Ref ASGGroupDesired
      LaunchTemplate:
        LaunchTemplateId: !Ref ASGPrivateEC2LaunchTemplate
        Version: 1 
      VPCZoneIdentifier: !Split [",", !ImportValue multi-az-vpc-private-subnet-id]
      Tags:
      - Key: Name
        Value: !Ref ASGInstanceName
        PropagateAtLaunch: 'true'
      TargetGroupARNs:
        - !Ref ALBPrivateEC2GroupTargetGroup
### ALB Security Group
  ALBPrivateEC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: ALB Private EC2 Group Security Group
      GroupName: Load Balancer Security Group
      SecurityGroupEgress:
        - 
         IpProtocol: -1
         CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !ImportValue multi-az-vpc-sg-public
      Tags:
        - Key: Name
          Value: Internal Load Balancer Security Group
      VpcId: !ImportValue multi-az-vpc
### Update Private SG Group to enable ALB to communicate on port 80
#  SecurityGroupPrivateIngress:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      GroupName: !Ref SecurityGroupPrivate
#      IpProtocol: tcp
#      FromPort: '80'
#      ToPort: '80'
#      SourceSecurityGroupId: !Ref ALBPrivateEC2SecurityGroup
#     SourceSecurityGroupName: !Ref SecurityGroupPrivate

### ALB Loadbalancer Config
  ALBPrivateEC2Group:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      IpAddressType: ipv4
      Scheme: internal
      Subnets:
        - !Select [0, !Split [",", !ImportValue multi-az-vpc-private-subnet-id]]
        - !Select [1, !Split [",", !ImportValue multi-az-vpc-private-subnet-id]]
        - !Select [2, !Split [",", !ImportValue multi-az-vpc-private-subnet-id]]
      SecurityGroups:
        - !ImportValue multi-az-vpc-sg-private
        - !Ref ALBPrivateEC2SecurityGroup

### ALB Listener
  ALBPrivateEC2GroupListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ALBPrivateEC2GroupTargetGroup
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: ALBPrivateEC2GroupTargetGroup
      LoadBalancerArn:
        Ref: ALBPrivateEC2Group
      Port: 80
      Protocol: HTTP

### ALB Target Group - Use Parameters to configure
  ALBPrivateEC2GroupTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      TargetType: instance
      HealthCheckIntervalSeconds: !Ref ALBHealthIntervalSec
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckPort: !Ref ALBHealthPort
      HealthCheckProtocol: !Ref ALBHealthTCP
      HealthCheckTimeoutSeconds: !Ref ALBHealthTimeout
      HealthyThresholdCount: !Ref ALBHealthThreshold
      Name: !Ref ALBName
      Port: !Ref ALBPort
      Protocol: !Ref ALBProtocol
      VpcId: !ImportValue multi-az-vpc
      Tags:
        - Key: Name
          Value: !Ref ALBName


### Outputs
Outputs:
  ASGPrivateEC2Group:
    Description: Private Auto Scaling Group
    Value: !Ref ASGPrivateEC2Group
    Export:
      Name: !Sub "${AWS::StackName}-asg-priv-001"

  ASGPrivateEC2LaunchTemplate:
    Description: Launch Template for Private EC2 Fleet
    Value: !Ref ASGPrivateEC2LaunchTemplate
    Export:
      Name: !Sub "${AWS::StackName}-asg-lt-priv-001"
  
  ALBPrivateEC2Group:
    Description: ALB for Back-End Instance
    Value: !Ref ALBPrivateEC2Group
    Export:
      Name: !Sub "${AWS::StackName}-alb-priv-001"

  ALBPrivateEC2GroupTargetGroup:
    Description: ALB for Back-End Instance
    Value: !Ref ALBPrivateEC2GroupTargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-alb-priv-tg-001"